### ISSUE TITLE
Please add a license to this project

### ISSUE THREAD

**Issue by rswgnu** [eliasdabbas/dashboardom#2]
Great set of dashboards.  Please add a license to this project, so usage details are clear.  Thanks.

**Comment by eliasdabbas** [comment]
Thanks @rswgnu ! 

Glad you liked them... 

Good idea. I just did. (Note that this app is just a container with iframes, where each dashboard is a separate app/repo, I'll add licenses to those as well).

**Comment by rswgnu** [comment]
Great, thanks.
